### ISSUE TITLE
seatID

### ISSUE THREAD

**Issue by studying1232** [runoob09/xxt_library_seat#2]
我们学校使用的是新系统，但是进行sign操作的时候会报错ERROR - 发生错误,('seatId',)，尝试旧版本命令的话，你的日志中好像并没有给出如何获取本学校的seatID

**Comment by runoob09** [comment]
1.seatId不存在的问题已经修复
2.seatId的获取逻辑十分复杂，目前仅支持抓包获取，抓包获取到的seatId和学校我会同步更新
